CREATE TABLE [Clarity].[EssentialHspAccount]
(
[ACCOUNT_CLASS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_BASECLS_HA_C] [numeric] (38, 0) NULL,
[ACCT_BILLED_DATE] [datetime] NULL,
[ACCT_BILLSTS_HA_C] [numeric] (38, 0) NULL,
[ACCT_CLASS_HA_C] [varchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_CLOSE_DATE] [datetime] NULL,
[ACCT_FIN_CLASS_C] [varchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_SLFPYST_HA_C] [numeric] (38, 0) NULL,
[ACTUAL_COINS_AMT] [numeric] (18, 2) NULL,
[ACTUAL_COPAY_AMT] [numeric] (18, 2) NULL,
[ACTUAL_DED_AMT] [numeric] (18, 2) NULL,
[ACTUAL_NCVD_AMT] [numeric] (18, 2) NULL,
[ADM_DATE_TIME] [datetime2] NULL,
[ADM_DEPT_DESC] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADM_PROV_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMISSION_PROVIDER] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMISSION_SOURCE_C] [varchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMISSION_SRC_EPT_C] [nvarchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMISSION_TYPE_C] [numeric] (38, 0) NULL,
[ADMIT_CATEGORY] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMIT_CATEGORY_C] [numeric] (38, 0) NULL,
[ADMIT_DEPT_ID] [numeric] (18, 0) NULL,
[ADMIT_DX_TEXT] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMIT_SOURCE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMIT_TYPE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASSOC_AUTHCERT_ID] [numeric] (18, 0) NULL,
[ATTENDING_PROV_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTENDING_PROVIDER] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BAD_DEBT_AGENCY_ID] [numeric] (18, 0) NULL,
[BAD_DEBT_BUCKET_ID] [numeric] (18, 0) NULL,
[BAD_DEBT_FLAG_YN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BASE_CLASS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_STATUS] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTHWEIGHTGRAMS] [numeric] (18, 0) NULL,
[CODED_CONTACT_CSN] [numeric] (18, 0) NULL,
[COLL_AGENCY_NAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMBINE_RSN_C] [numeric] (38, 0) NULL,
[COPAY_REASON_FIELD] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COVERAGE_ID] [numeric] (18, 0) NULL,
[CUSTOM_LOC] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISCH_DATE_TIME] [datetime2] NULL,
[DISCH_DEPT_DESC] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISCH_DEPT_ID] [numeric] (18, 0) NULL,
[EXTERN_AR_FLAG_YN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRST_FULL_SP_DT] [datetime] NULL,
[FIRST_SELF_PAY_DT] [datetime] NULL,
[FRST_STMT_DATE] [datetime] NULL,
[GUARANTOR_ID] [numeric] (18, 0) NULL,
[HAS_OPEN_OVRP_BD_YN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HAS_OPEN_UNDP_BD_YN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HSP_ACCOUNT_ID] [numeric] (18, 0) NULL,
[HSP_ACCOUNT_NAME] [varchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IP_ADMIT_DATE_TIME] [datetime2] NULL,
[LAST_FULL_SP_DT] [datetime] NULL,
[LAST_STMT_DATE] [datetime] NULL,
[LOC_ID] [numeric] (18, 0) NULL,
[LOCATION_ABBR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOM_HSP_ACCT_ID] [numeric] (18, 0) NULL,
[MOM_PATIENT_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MS_DRG] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPEN_COR_BDC_YN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPEN_DENIAL_BDC_YN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPEN_RMK_BDC_YN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OUTSOURCE_FLAG_YN] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAT_DOB] [datetime] NULL,
[PAT_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAT_SEX_C] [varchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAT_SSN] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PATIENT_MRN] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREBILL_BUCKET_ID] [numeric] (18, 0) NULL,
[PRIM_ENC_CSN_ID] [numeric] (18, 0) NULL,
[PRIM_SVC_HA_C] [varchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARY_FINANCIAL_CLASS_NAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARY_PAYOR_ID] [numeric] (18, 0) NULL,
[PRIMARY_PAYOR_NAME] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARY_PLAN_ID] [numeric] (18, 0) NULL,
[PRIMARY_PLAN_NAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARY_SERVICE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRORATED_PAT_LIAB] [numeric] (12, 2) NULL,
[REC_CREATE_USER_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RECORD_CREATE_DATE] [datetime] NULL,
[RECORD_CREATION_ID] [numeric] (18, 0) NULL,
[SELF_PAY_BUCKET_ID] [numeric] (18, 0) NULL,
[SELF_PAY_YN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERV_AREA_ID] [numeric] (18, 0) NULL,
[SP_LEVEL_C] [numeric] (38, 0) NULL,
[TOT_ACCT_BAL] [numeric] (18, 2) NULL,
[TOT_ADJS] [numeric] (18, 2) NULL,
[TOT_CHGS] [numeric] (18, 2) NULL,
[TOT_PMTS] [numeric] (18, 2) NULL,
[MIN_DAYS_END_DATE] [datetime] NULL,
[Patient_Status_C] [varchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMBINE_ACCT_ID] [numeric] (18, 0) NULL,
[CODING_STATUS_C] [int] NULL,
[CODING_STS_USER_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODING_DATETIME] [datetime] NULL,
[CODING_STATUS_NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPLETN_STS_HA_C] [int] NULL,
[COMPLETN_STS_NAME] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FINAL_DRG_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERRING_PROV_ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERRING_PROVIDER] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ixCombAcct] ON [Clarity].[EssentialHspAccount] ([COMBINE_ACCT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_DischDtHar] ON [Clarity].[EssentialHspAccount] ([DISCH_DATE_TIME]) INCLUDE ([HSP_ACCOUNT_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ix_Pk_HspAccountId] ON [Clarity].[EssentialHspAccount] ([HSP_ACCOUNT_ID]) WITH (IGNORE_DUP_KEY=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PrimEncCsnID] ON [Clarity].[EssentialHspAccount] ([PRIM_ENC_CSN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_SpBktID] ON [Clarity].[EssentialHspAccount] ([SELF_PAY_BUCKET_ID]) ON [PRIMARY]
GO
