IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SCLHS\_SQLSERVICE')
CREATE LOGIN [SCLHS\_SQLSERVICE] FROM WINDOWS
GO
CREATE USER [SCLHS\_SQLSERVICE] FOR LOGIN [SCLHS\_SQLSERVICE]
GO
